[package]
name = "gravyan"
description = "A simple terminal-based gravity calculator"
repository = "https://github.com/lordpaijo/gravyan"
license = "MIT"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.28"
crossterm = "0.28"
